### ISSUE TITLE
Failures for newest woothee spec

### ISSUE THREAD

**Issue by ianks** [woothee/woothee-rust#14]
When updating [fast_woothee](https://github.com/ianks/fast_woothee) and pulling down the latest woothee repo, I noticed these failures. Figured I'd document 'em:

```
  1) FastWoothee pc_misc: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 YaBrowser/17.11.1.1087 (beta) Yowser/2.5 Safari/537.36 name
     Failure/Error: expect(r[attr].to_s).to eql(e[attr.to_s])
     
       expected: "Yandex Browser"
            got: "Chrome"
     
       (compared using eql?)
     # ./spec/fast_woothee_spec.rb:28:in `block (5 levels) in <top (required)>'

  2) FastWoothee pc_misc: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 YaBrowser/17.11.1.1087 (beta) Yowser/2.5 Safari/537.36 version
     Failure/Error: expect(r[attr].to_s).to eql(e[attr.to_s])
     
       expected: "17.11.1.1087"
            got: "62.0.3202.94"
     
       (compared using eql?)
     # ./spec/fast_woothee_spec.rb:28:in `block (5 levels) in <top (required)>'

  3) FastWoothee pc_windows: Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 YaBrowser/18.1.1.839 Yowser/2.5 Safari/537.36 name
     Failure/Error: expect(r[attr].to_s).to eql(e[attr.to_s])
     
       expected: "Yandex Browser"
            got: "Chrome"
     
       (compared using eql?)
     # ./spec/fast_woothee_spec.rb:28:in `block (5 levels) in <top (required)>'

  4) FastWoothee pc_windows: Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 YaBrowser/18.1.1.839 Yowser/2.5 Safari/537.36 version
     Failure/Error: expect(r[attr].to_s).to eql(e[attr.to_s])
     
       expected: "18.1.1.839"
            got: "63.0.3239.132"
     
       (compared using eql?)
     # ./spec/fast_woothee_spec.rb:28:in `block (5 levels) in <top (required)>'

  5) FastWoothee smartphone_android: Mozilla/5.0 (Linux; Android 9; SM-N960F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.105 Mobile Safari/537.36 os_version
     Failure/Error: expect(r[attr].to_s).to eql(e[attr.to_s])
     
       expected: "9"
            got: "UNKNOWN"
     
       (compared using eql?)
     # ./spec/fast_woothee_spec.rb:28:in `block (5 levels) in <top (required)>'
```

**Comment by hhatto** [comment]
@ianks 
Sorry, I may not have been able to push the latest source to the origin's master branch.
Could you try again `rake spec` now?

```
> git diff
diff --git a/spec/fast_woothee_spec.rb b/spec/fast_woothee_spec.rb
index f3ed99c..5c0fab0 100644
--- a/spec/fast_woothee_spec.rb
+++ b/spec/fast_woothee_spec.rb
@@ -15,7 +15,7 @@ end

 known_failures = [
   # https://github.com/woothee/woothee-rust/issues/14
-  "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 YaBrowser/17.11.1.1087 (beta) Yowser/2.5 Safari/537.36"
+  # "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 YaBrowser/17.11.1.1087 (beta) Yowser/2.5 Safari/537.36"
 ]

 describe FastWoothee do
> rake spec
checking for cargo... yes
/Users/hattorihideo/.cargo/bin/cargo rustc --release --lib -- -C link-args=-Wl,-undefined,dynamic_lookup -Wl,-multiply_defined,suppress
    Finished release [optimized] target(s) in 0.03s
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby -I/Library/Ruby/Gems/2.3.0/gems/rspec-support-3.8.0/lib:/Library/Ruby/Gems/2.3.0/gems/rspec-core-3.8.0/lib /Library/Ruby/Gems/2.3.0/gems/rspec-core-3.8.0/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb

FastWoothee
  has a version number
  crawler_nonmajor: emBot-GalaBuzz/Nutch-1.0 (http://emining.jp/; em@galabuzz.jp)
    name
    category
    crawler?
    :
Finished in 0.13572 seconds (files took 0.31466 seconds to load)
1171 examples, 0 failures
```
